- id: '1733612849910'
  alias: Turn off Christmas Lights
  description: ''
  triggers:
  - trigger: time
    at: '23:59:00'
  conditions: []
  actions:
  - type: turn_off
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: db58d52836ed6022c8eadefb7767df54
    domain: switch
  - type: turn_off
    device_id: 5e3d6a02de3b51fc8886476057177b9e
    entity_id: b78bf48819a0ff2534e9f1aaccf09f11
    domain: switch
  mode: single
- id: '1733707407241'
  alias: Turn on xmas lights
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - type: turn_on
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: db58d52836ed6022c8eadefb7767df54
    domain: switch
  - type: turn_on
    device_id: 5e3d6a02de3b51fc8886476057177b9e
    entity_id: b78bf48819a0ff2534e9f1aaccf09f11
    domain: switch
  mode: single
