- id: '1607216364655'
  alias: Auto turn off all
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - type: turn_off
    device_id: 91daf010f807c3a44d72ee9cff1cc80b
    entity_id: switch.xmas_tree
    domain: switch
  - type: turn_off
    device_id: c17e000a44e419ae49e7d7a4edab3458
    entity_id: switch.xmas_lights
    domain: switch
  - type: turn_off
    device_id: 6c1993995decdfdf36ac7bb2fdb2368f
    entity_id: switch.xmas_tree_2
    domain: switch
  - type: turn_off
    device_id: 707956b1edb51d3598cb333bed2ca308
    entity_id: light.small_lamp
    domain: light
  mode: single
- id: '1607825394775'
  alias: No living room motion turns lights off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 361652f3b2369e4cdd6ba6b223801aec
    entity_id: binary_sensor.hue_motion_sensor_2_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: d2b5408d1062516d36e34d9140e2216f
    entity_id: light.hue_color_lamp_1
    domain: light
  - type: turn_off
    device_id: 91daf010f807c3a44d72ee9cff1cc80b
    entity_id: switch.xmas_tree
    domain: switch
  - type: turn_off
    device_id: c17e000a44e419ae49e7d7a4edab3458
    entity_id: switch.xmas_lights
    domain: switch
  mode: single
- id: '1673494286948'
  alias: Upstairs motion turn on lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: ffaf1c77aac750acf342bfc43cbee95b
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 1b1c140b6b4a463d72870792b24cff96
    entity_id: binary_sensor.hue_motion_sensor_2_motion
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    below: 15
    attribute: light_level
  action:
  - type: turn_on
    device_id: 5e3d6a02de3b51fc8886476057177b9e
    entity_id: switch.stair_lighta
    domain: switch
  - type: turn_on
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: switch.xmas_lights
    domain: switch
  mode: single
