- id: '1607216364655'
  alias: Auto turn off all
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - type: turn_off
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: db58d52836ed6022c8eadefb7767df54
    domain: switch
  mode: single
- id: '1607825394775'
  alias: No living room motion turns lights off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 1b1c140b6b4a463d72870792b24cff96
    entity_id: 8f2f5eb001f029261e9d838392bd7ce7
    domain: binary_sensor
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: db58d52836ed6022c8eadefb7767df54
    domain: switch
  mode: single
- id: '1673494286948'
  alias: Upstairs motion turn on lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: ffaf1c77aac750acf342bfc43cbee95b
    entity_id: binary_sensor.hue_motion_sensor_1_motion
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 1b1c140b6b4a463d72870792b24cff96
    entity_id: binary_sensor.hue_motion_sensor_2_motion
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: sensor.hue_motion_sensor_1_light_level
    below: 15
  action:
  - type: turn_on
    device_id: fdd158316aba6f2bf5487c0c74b04341
    entity_id: db58d52836ed6022c8eadefb7767df54
    domain: switch
  mode: single
