frontend:
conversation:
shopping_list:
#updater:
sun:
history:
logbook:
config:
system_health:
bluetooth:
zeroconf:

lovelace:
  mode: yaml

homeassistant:
  name: Home
  unit_system: imperial
  temperature_unit: F
  country: US
  currency: USD
  time_zone: !secret timezone
  internal_url: !secret internal_url
  latitude: !secret latitude
  longitude: !secret longitude

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

