frontend:
shopping_list:
updater:
sun:
history:
logbook:
config:
system_health:
zeroconf:
        #speedtestdotnet:
        #   scan_interval: '00:15'

lovelace:
  mode: yaml
  dashboards:
    stack-monitoring:
      title: Monitoring
      icon: mdi:chart-bar-stacked
      show_in_sidebar: true
      mode: yaml
      filename: dashboards/stack-monitor.yaml
    plant-hydration:
      title: Plants
      show_in_sidebar: true
      mode: yaml
      filename: dashboards/plant-hydration.yaml

homeassistant:
  name: Home
  unit_system: imperial
  temperature_unit: F
  time_zone: !secret timezone
  internal_url: !secret internal_url

#hue:
#  bridges:
#    - host: 192.168.0.197
#      allow_unreachable: true
#      allow_hue_groups: true

wemo:
  discovery: true
  static:
    - 192.168.0.173
    - 192.168.0.241

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: command_line
    name: gw1000_indoor_temp
    command: "curl http://192.168.0.180:4545/query?query=gw1000_tempinf"
    scan_interval: 15
