title: Home!
views:
  - title: Home
    path: home
    badges:
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - title: Bedroom
        type: entities
        entities:
          - entity: light.h60a1
            name: Ceiling Light
            icon: mdi:light-recessed
          - type: button
            name: Prep for bed
            entity: script.prep_for_bed
            icon: mdi:sleep
            tap_action:
              action: call-service
              service: script.prep_for_bed
          - type: button
            name: Evening Lights
            icon: mdi:weather-night
            entity: script.bedroom_light_evening_mode
            tap_action:
              action: call-service
              service: script.bedroom_light_evening_mode
          - type: button
            name: Daytime lights
            icon: mdi:brightness-5
            entity: script.bedroom_light_daytime_mode
            tap_action:
              action: call-service
              service: script.bedroom_light_daytime_mode
