title: Home!
views:
  - title: Home
    path: home
    badges:
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - title: Bedroom
        type: entities
        entities:
          - entity: light.h60a1
            name: Ceiling Light
            icon: mdi:light-recessed
