title: Home!
views:
  - title: Home
    path: home
    badges:
      - entity: binary_sensor.updater
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: true
      - title: Living Room
        type: entities
        entities: 
          - light.white_lamp
          - entity: light.hue_color_lamp_1
            name: Large Lamp
          - entity: switch.xmas_lights
            icon: mdi:string-lights
          - entity: switch.xmas_tree
            icon: mdi:pine-tree
          - entity: binary_sensor.hue_motion_sensor_1_motion
            name: Stairs Motion
          - entity: sensor.hue_motion_sensor_1_temperature
            name: Staits Temp
      - title: Office
        type: entities
        entities:
          - light.small_lamp
      - title: Actions
        type: button
        entity: script.script_1
        name: Bedtime
        icon: mdi:sleep
